### ISSUE TITLE
[ Draft ] - Organization page UI/UX improvements

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#201]
Adapt the current voting page to apply to the UI/UX improvements after the 1st feedback session and revamp:

**Tasks**:
- [x] Reduce max weight (1200px?) of the whole page
- [x] Add a card as the org element (top element)
- [x] Move the Title as 1st item. Increase font size (32px). 
- [x] Move the "address" component to the right
- [x] Create the "empty state" new card with the proposed design
- [x] Adapt the cards of the elections:
     - [x] Order the elements as the screenshot (title -> label + calendar -> description -> footer). 
     - [x] Reduce space between the cards (gap)  
     - [x] Style the card as the screenshot.

**Empty State:**
![org_empty](https://github.com/vocdoni/ui-scaffold/assets/6894329/5454dbfb-8e2b-49fe-937d-fb0ecb9cd433)

**With Elections:**
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/244c20ca-296e-4cc9-84df-9b7cdfe21155)
