### ISSUE TITLE
Header component UI/UX improvement

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#202]
Adapt the header:

**Tasks:**
- [ ] Remove the box-shadow.
- [x] Reduce logo & text size of the header. 
- [ ] Remove the background.
- [x] When the user is logged in, move the "lang" drop-down inside the general menu.
- [x] Add the needed logic for display different header types depending on the user status (not logged / logged without org / logged with org).
- [x] Adapt visually the different buttons (border radius, background, color, paddings, margins, etc.).
- [ ] Add the switcher component (without functionality for now).
- [x] Adapt the new drop-down menu with the lang on it, the "wallet component" + tokens, and the other options on it.
- [x] Order the different elements on the header, as shown in the images.
- [ ] Add  ` backdrop-filter: blur(24px);` to the header.

**Not Logged:**
![magenta-marshmallow-2165aa netlify app_](https://github.com/vocdoni/ui-scaffold/assets/6894329/97b830b4-49d9-4969-ac7b-ffd40fd74696)

**Logged without org:**
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/1060ca7c-4b1e-4130-a2db-6e82c1aecd9b)

**Logged with org:**
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/5f0323b3-e64a-4096-8152-c01f6a86f7fe)

Visually, it should look like this:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/ac5377a4-dd67-46c2-a389-f49e1d7b482a)
