### ISSUE TITLE
CSV adapt the voting UI/UX 

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#204]
When the census comes from a spreadsheet (CSV) the voting behavior is different, instead of vote with the Metamask, a popup with the data is shown and the voter fills the information. Also, when the user submit the vote, a "Confirm" modal should appear with the selected options and a "Logout" button when is logged with their custom data should appear. 

- [ ] Finish design (@jpaulet )

**Tasks:**
- [ ] Style the "Auth" popup 
- [ ] Style the "Confirm" popup 
- [ ] Add the "Logout" banner & functionality
