### ISSUE TITLE
Pre-launch improvements checklist

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#287]
Implement the following changes and improvements in each page/component:

**Org page:**
- [x]  Header card: background:white  (now it's transparent or grey)
- [x]  Space between "Election" and the following card reduced
- [x]  Make all the illustrations smaller (width:200px) and move 150px left. Reduce text size:  
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/a8a19a5f-c69c-4650-888e-7dd7a742b7ba)

**Process creation:**
- [x]  In the "Preview" page, if the Description is a MD, render it as MD. (https://github.com/vocdoni/ui-scaffold/issues/264)

**Census creation:**

- [x] #297

Address List:
- [x] In the Address census, add a label in "your" address to mark as yours
- [x] The list margins are different between the 1st row and the others
- [x] Add as the image of "your wallet was automatically added to the list" below the addresses box
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/1c1c7406-6886-4309-9ab3-ea620e4de6c3)

**Voting page:**
- [x] Reduce "Voting" card to max-width: 300px and center it (margin-right:55px) in desktop view
- [x] Reduce the "Voting" card height and padding in mobile view. Reduce the "Status" and "Vote nº" text size to make it smaller.
- [x] #299

Confirm Modal: 
- [ ]  Increase vertical padding (top-bottom)
- [ ]  Increase width (min-width:35%)
- [ ]  Solve image reference not loading (wrong path)
- [ ]  Change shadow from list of choices (rgba(128, 128, 128, 0.42) 1px 1px 1px 1px) & add more padding
- [ ]  Increase the padding inside the choices
- [ ]  Add more vertical space between the "Please confirm your choices" and the text
- [ ]  Improve the "x" icon
- [ ]  Increase the background black (0.75)
- [ ]  Remove the extra "-" in the end of the phrase
- [ ]  Modify the "X" times to the real nº
