### ISSUE TITLE
Anonymous flows

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#355]
We should adapt the flows to the new anonymous voting. 

**Non-Anonymous Voting Flows:**

Signer:  Connect -> Select Wallet -> Vote -> Confirm -> Success
Wallet:  Identify -> Fill form -> Vote -> Confirm -> Success

**New Anonymous Voting Flows:**

Signer: Connect -> Select Wallet -> Authenticate -> Vote -> Confirm -> Voting Modal -> Success
Wallet: Identify -> Fill form + password -> Vote -> Confirm -> Voting Modal -> Success

____

When we detect that the voting process is anonymous, different uses cases should be applied depending on the census type used:

### Signer Accounts (Token Voting & Wallet addresses):

With "signer accounts", the voter will encrypt the information with their private_key by signing the transaction and generating the SIK in this action, we don't need to add a "password".

**1 - Identification Phase:**
When entering for first time, all the public voting info + a "Identify" button should be visible. Clicking into the "Identify" button will show the popup for selecting the wallet connector.

**2 - Authentication Phase:** 
After connecting, a new modal appears with the "Authentication" flow:

**2.1 [Already registered ]** 
A popup will appear, with a text that explains that with anonymous voting, we need to verify you identity by signing a TX (SIK). 

SIK Authentication:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/199df49c-c802-446e-8fc5-ec3427bac66c)

**2.2 [ Not Registered ]** 
A new popup text on the modal, explaining that before voting, you need to create a SIK + an account by signing 2 TX, explaining that it's free and only needs to be done once. 

SIK Register + Account Creation:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/f196210f-3daa-4789-ae82-a1e0bcbda0c6)

_[In both cases, 2.1 and 2.2, we should store the SIK in the user storage to use it while the tab is not closed.]_

3 - Show the voting page, with all the proper info on it (if he voted or no, showing the appropriate messages and buttons).

____

### Internal Wallets (Custom Data (CSV)):

With "internal wallets" we have the control over the wallet and the signatures can be done in the background without the user noticing, but the organizer can impersonate the voter as he has all the information or check what they voted. For that reason, we introduce the "password" into the flow, to add a external info that only the voter knows.

**1 - Identification Phase:**
Without "Identify", the voting info should be visible. Clicking into the "Idenfity" button will show the form popup for entering the CSV data.

**2 - Authentication Phase:**
After connecting successfully, a new button appears with a "Authenticate": 

2.1 Not registered & no password.
If the user hasn't set the password, just after identifying, we change the "form" content to this new popup with the password setting, after that, the user can vote (in the background, we also create the account):

![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/8e19e2a0-fc7c-4bd0-a97a-b1d1a486eea7)

2.2 Registered with password:
If the user has set previously a password, when clicking the "Authenticate" button, a new popup will appear with the password flow. Then, the user will be able to vote, re-vote or check it's vote:

![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/01076258-4249-4105-8e53-8710a63bcacb)

____

### Both Flows (Signers and Wallets)

New popup while voting:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/e607688e-8ac2-4596-ada5-6ce9d36520e4)

**TASKS**:
- [ ]  Detect if the voting is anonymous
- [ ] Detect if the voting is signer/wallet
- [ ] Add the new flow in the signer votings
     - [ ] Add the "Authenticate" button with a text explaining it 
     - [ ] Show the new signer popup
     - [ ] Pre-fetch the circuit files (workers)
     - [ ] Add the modal when voting explaining the waiting time and process 
- [ ] Add the new flow in the wallet votings
     - [ ] Add the password in the form popup
     - [ ] Pre-fetch the circuit files (workers)
     - [ ] Add the modal when voting explaining the waiting time and process
 - [ ] Make sure the voter can only view the vote after authenticate in both cases 
 - [ ] Test

**Comment by p4u** [comment]
I would not show the "Connect" nor "Authenticate" buttons on the election screeen, but instead in the header (as usual). 

Take into account that the anonymous election results can be seen, even without authentication.

So the only thing we need to disable is the "Vote" button (which is disabled until Authentication done) and maybe a sign saying "you need first to authenticate". 

Once user have authenticated it can either Vote or Verify Vote.

**Comment by jpaulet** [comment]
We should discuss if we unify the "Wallet" form flow into 1 step (identification + password) or in 2 different modals (1st identification -> password). 

I made a test for the 1 step form, but it can lead to a misleading info, as we still don't know who the voter is and if he/she already created the password or not:

![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/6493dd63-7738-4fa4-8e26-1befea603c0b)

**Comment by p4u** [comment]
Some text corrections:

+ 100% anonymous voting sounds weird, just "anonymous voting" please 
+ 2.1: the current text is inaccurate, the user is not "signing a transaction", instead I would say something like "We need to generate your secret identity key (SIK) by performing a signature". Also please remove the "The signature is free and secure", maybe just say "This operation does not have any cost for your".
+ in general do not say "SIK" key, since SIK already stands for `KEY`. 
+ 2.2:  I'd replace with `To participate in the anonymous voting process, you need to create a secret identity key (SIK) by signing a text message. Then we need to sign a transaction to create your account and register it into the blockchain. Note that none of both operations have any cost for your.`

I'd also ask someone to review the texts, if we can have it in a text file or something, I can ask Isaac to do so.

**Comment by p4u** [comment]
In geneneral the flow LGTM.
