### ISSUE TITLE
Finish v1 of UI-scaffold

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#49]
As Vocdoni we want to be able to do a soft-lunch of the v1 of the ui-scaffold with the following acceptance criteria:

- List created orgs & processes
- Org view and processes list
- Process detail and questions/options visualization
- Process status management and lifecycle progress (upcoming, ended, canceled, ongoing, results)
- Results visualization
- Vote functionality and vote proof
- Lang switch, menus, header & footer
- Create process v0.1
- Adapt the styles and layout to the design

**Detected Pending tasks:**

**Functional**:
- [ ] Remove the "Read more/Read less" when there is not enough content
- [ ] The process list should have the inverse order (the new processes first)
- [ ] Add the search functionality for processes
- [ ] Add the "Active" functionality in the process list
- [ ] Hide sharing buttons
- [x] #51
- [x] Remove the account creation when a voter needs to vote (https://github.com/vocdoni/ui-components/issues/40)
- [x] #53

**Visuals**:
- [x] Add a "on-hover" effect in the orgs/processes cards, when hover change the box-shadow to 'gray 0px 2px 4px' 
- [x] Recover hover in all buttons and links
- [x] https://github.com/vocdoni/ui-components/issues/42
- [x] Unify buttons colors and text colors in all pages (primary color & secondary color).
- [x] Review texts and translate everything to Spanish and Catalan
- [x] Implement the "404" page: https://www.figma.com/file/bwRMdpZzB1ZIO7VihD8XK0/%F0%9F%97%B3-Voting-UI?type=design&node-id=3601-6909&t=En0rUnF6VoM8nafH-4
- [x] Remove header buttons background, and only add the "on-hover" background (var(--chakra-colors-gray-200)):
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/0792bf2d-6bd2-4514-b79e-d43beee80614)
- [x] Card on-hover shadow: `#808080b5 0px 2px 4px` (add 0.2 transition if possible)
- [x] Add more horizontal padding in the "My list" button.
- [ ] Improve "vote proof" element:
  - [x] Change the "i" icon for a "check" icon (changed in ui-components)
  - [ ] Move the icon to fit in the left side, centered vertically with the whole div, reducing vertical space
  - [ ] Unify the text in one line: "To verify your vote, you can use this unique id:"
  - [x] Add `border-radius:8px; padding: 4px 15px; margin-top: 10px; margin-bottom: 10px;` to the id element (in white)
- [x] Add the same "on-hover box-shadow" that the cards have to the options buttons:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/fd2abc6a-2d99-4e08-93fe-83aa51729ad3)
- [x] Remove the background to the "play" option:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/c0f00237-a381-40f6-b3b5-ed207cf3d38b)
- [x] Change "Create Process" background to a gradient if possible: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/133f3aa3-b493-4bf9-893e-61649e61d7bb)
- [x] Unify the primary color with "#00624F;" (text, vote proof, selected options)
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/b772696b-5037-4e80-9d1b-8b650d4c6dcb)
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/309a9227-4361-45a0-8bef-71b25729d877)
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/1890dc04-6231-4564-8883-2b4b9dc03fe8)
- [x] Align vertically the "lang" drop-down by adding "margin-top:-2px;" on it
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/2d6a60cb-7aff-4499-a686-fecb72e854b9)
- [x] Improve the "status management" pill, making it fit inside the card, without background, reduce opacity to 0.5 and reduce size with a `scale(0.8)`, add "onhover" effect (opacity to 0.75) and align them vertically:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/9381424b-e39b-4d22-88e4-e0f23d32fc4d)
- [ ] Add the default placeholder image if no image is set in the "org view" 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/998e4748-76bf-4456-8658-21fc7a118151)
- [x] Add hover effect in the elements of the submenu
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/07da01ca-f41b-4f65-ab7a-a33175c9c449)
- [x] Add hover effect to the "org action button"  (hover and active: background color #003128). 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/5082d80a-58de-4a92-993c-fbaed3c2b136)
- [x] #52
- [x] Unify the lines width and color: 
     - [x] Make all the lines (vertical one between Questions | Results) and the vertical one in the top-right area with the same width and color than the horizontal one
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/51aa6fbd-a605-4fec-be37-ae919d372585)
- [x] Add vertical margins in the "org card":
    - [x] 5px between the orgName and the electionTitle
    - [x] 20px between the electionTitle and the election details
    - [x] Same in the "election card"
- [x] #54
- [ ] 

Bugs: 
- [ ] If the voter disconnects the wallet, the "Your vote is submitted..." element is not removed from the UI. 

Once finished, we will do a intensive QA (v2).
