### ISSUE TITLE
Add anonymous rounded census information

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#520]
When selecting the anonymous setting for a voting, we need to explain the "rounded census" in a general way and specific (show the accuracy %):

![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/4c15725d-d085-42bd-bba6-4e4c36888002)

Text: 

> Disclaimer: If voters use token voting power (public onchain),  to enhance anonymity, weights are grouped into similar balances, rounded down. This sacrifices some accuracy but preserves identity by unlinking balances from wallets.

Specific Accuracy:

In the "Preview page" add a new row with the accuracy (returned by the SDK) with a "?" icon with a tooltip with the same text as above:
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/44a6c959-7734-498f-8548-0be886ee8c57)

**ToDo:**
- [x] Add the generic text
- [x] Add the specific text with the icon + popup
- [x] Only show the specific message when "anonymous + token voting" are selected
- [x] Test it
