### ISSUE TITLE
Create the new landing for Vocdoni.app

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#531]
As Vocdoni we need to create a new landing that focuses on showcase our product, better explain our offering and increase leads. 

Implement the following landing page, as a new theme. This page will replace the current one for `app.vocdoni.io`. 

**Tasks:**
- [x] Create the base page
     - [x] Page structure
     - [x] Layout:
          - [x] Navbar 
          - [x] Hero + clients
          - [x] Benefits
          - [x] Contact
          - [x] Process
          - [x] FAQ
          - [x] Contact2
          - [x] Footer
- [x] Add the title copies and the "lorem ipsum" in the descriptions
- [x] Create the copies for the whole page
- [x] Add the images, icons and visual parts
- [x] Responsive view

Visual Reference:

![vocdoni_new_landing](https://github.com/vocdoni/ui-scaffold/assets/6894329/734a0fcd-299b-4216-bb82-59726303cc25)

Ref: https://quiety-next.themetags.com/desktop-app

**Comment by jpaulet** [comment]
- [ ] Center image into the div: `margin:0px auto;` 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/fd8b861f-8a36-4e15-9627-59bab106ab8c)

- [ ] Reduce the padding (top/bottom) in the hero section from 120px to 100px
- [ ] Use cases, make 3 cards per row, to unify with the 3 "radiobuttons" on top: 
![image](https://github.com/vocdoni/ui-scaffold/assets/6894329/9357577d-1899-4efe-b480-d469e07bdbf0)

- [ ] Navbar items: `font-weight:900; color:#0b163f;`
