### ISSUE TITLE
Add Gitcoin Support into the UI

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#542]
Work with the Gitcoin passport integration into the onvote UI:

As Vocdoni we want to offer a new census type (Gitcoin Passport) and the voting process creator will be able to define the minimum score needed to vote (1-100) as a pure integer (no decimals). Also, they can select different stamps and define the type of combination (OR/AND) of them. 

Each stamp is stored as a token in the Census3, under the type: "gitcoinpassport"

Example of the Census3 object returned by the API:

`{
      "ID": "0x000000000000000000000000000000000000006C",
      "type": "gitcoinpassport",
      "decimals": 0,
      "startBlock": 0,
      "symbol": "GPS",
      "totalSupply": "6461320",
      "name": "Gitcoin Passport Score",
      "synced": true,
      "defaultStrategy": 1,
      "chainID": 1,
      "chainAddress": "eth:0x000000000000000000000000000000000000006C"
}`

Visual Reference:
![Screenshot 2024-02-27 at 16-31-31 uizard](https://github.com/vocdoni/ui-scaffold/assets/6894329/4980d1ee-1929-47b8-8cff-1f995a3fe899)

Stamp List:
Idena, GTC Staking, Civic, Twitter, PHI, Gnosis Safe, Lens, Guild, Trusta Labs, Coinbase, Proof of Humanity, Linkedin, Google, ZKSync, NFT Holder, Discord, BrightID, Gitcoin, Snapshot, Github, ENS, EThereum, Holonym

**Tasks:**
- [x] Prepare visually how it will look the new census (Aulet)
- [x] Create a new census card "Gitcoin" where you can select the different stamps (checkboxes) and set a minimum score, then generate the according strategy.
- [x] Remove the Gitcoin from the token list, until we have the strategy (AND, OR)
- [x] Get the icons of each stamp from https://passport.gitcoin.co/#/dashboard
- [x] Create a voting process with the Gitcoin census, test the stamps, the min score and to vote with/without GP.
