### ISSUE TITLE
[EPIC] - Tech Pending and other major issues

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#8]
A "mess drawer" issue with anything still pending:

- [x] Update ElectionStatusBadge to use the new SDK election status (when available, see https://github.com/vocdoni/vocdoni-sdk/pull/113) + colorize it
  + [x] Also check logic related to the election status (like in `components/Process/View.tsx`, maybe we shall remove that `isOngoing`)
  + [x] And add some disabled logic based on that status to the ui-components form (to disable the options in case it's not ready or you just can't vote).
- [x] Add the vocdoni balance widget (and tune it to meet requirements too) - [blocked by design]
- [x] Check issue changing organization URL (go to an organization and then click on "my list", and you'll see the view does not refresh).
- [x] https://github.com/vocdoni/ui-scaffold/issues/21
- [x] https://github.com/vocdoni/ui-components/pull/14
- [x] Implement the action buttons in `react-components` (and add it to the default process view component) https://github.com/vocdoni/ui-components/issues/8.
- [x] Review found bugs: https://www.notion.so/aragonorg/Feedback-Voting-UI-a90d2111802c47f5802f53efad87a167
- [ ] Code hardcoded parts when the SDK & API requirements are satisfied - [blocked by API/SDK]
  + [x] List of other accounts' elections
  + [ ] Active/All filtering of elections - [blocked by API/SDK]

Feel free to suggest things that I may have missed (or even edit this issue if you have the permissions, ofc).
