### ISSUE TITLE
[EPIC] Create untitled theme

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/ui-scaffold#845]
Some of the following require the final definition of colors, which we don't have yet. For that reason, components related to the color scheme are after the ones not requiring it.

The list's created this way so you can split it into multiple issues. Note each section requires both the `light` and `dark` variants to be done before merging.

- [x] #846
- [x] #848
  + [x] Style Inputs
		 Note this includes all input variants, like having side elements and errors.
  + [x] Style Checkboxes
		 Note: checkboxes are squared :)
  + [x] Style Radio buttons
         Note: radio buttons are rounded :)
  + [x] Style input dropdowns
  + [x] Style file uploaders
  + [x] Text area
- [x] #863
- [x] #850
- [x] #869
- [x] #851
- [x] #852
- [x] #853
- [x] #854

Require a defined color scheme:
- [x] #866
- [ ] Ensure color scheme does not break already built components (tags, badges, tabs, checkboxes, radios...)

Pages and sections (require all the above):
- [ ] Auth (login, signup, password forgot...)
- [ ] Page 404
- [ ] ...

**Comment by elboletaire** [comment]
Closing and focusing on the review one and the missing 404 page:
- #875 
- #878
