### ISSUE TITLE
SaaS Review UI/UX: Problems, Improvements and Fixes

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-scaffold#894]
- [x] **SignIn Page**: https://github.com/vocdoni/ui-scaffold/issues/912
- [x] **Register page**: https://github.com/vocdoni/ui-scaffold/issues/913
- [x] **Account created successfully page**: https://github.com/vocdoni/ui-scaffold/issues/914
- [x] **Create your organization**: https://github.com/vocdoni/ui-scaffold/issues/915
- [x] **Organization Admin Page**:  https://github.com/vocdoni/ui-scaffold/issues/916
- [x] **Admin Dashboard**: https://github.com/vocdoni/ui-scaffold/issues/917
- [x] **Create Process**: https://github.com/vocdoni/ui-scaffold/issues/918
- [x] **Public Voting Page**: https://github.com/vocdoni/ui-scaffold/issues/919
- [x] **Admin Sidebar Navigation**: https://github.com/vocdoni/ui-scaffold/issues/920
- [x] **Voting process Details**: https://github.com/vocdoni/ui-scaffold/issues/908
- [x] **Password Recovery**: https://github.com/vocdoni/ui-scaffold/issues/910
- [x] **404 Page**: https://github.com/vocdoni/ui-scaffold/issues/878
- [x] **Tabs**: https://github.com/vocdoni/ui-scaffold/issues/891
- [x] **Toast**: https://github.com/vocdoni/ui-scaffold/issues/911
- [x] **Errors**: https://github.com/vocdoni/ui-scaffold/issues/893
- [x] **Popup Invite Admin**: https://github.com/vocdoni/ui-scaffold/issues/924
- [x] **Public voting page**: https://github.com/vocdoni/ui-scaffold/issues/909
